-- Plugin highlight groups
local M = {}

function M.get(c)
  return {
    -- GitSigns
    GitSignsAdd = { fg = c.states.success },
    GitSignsChange = { fg = c.accent.primary },
    GitSignsDelete = { fg = c.states.danger },
    GitSignsAddNr = { fg = c.states.success },
    GitSignsChangeNr = { fg = c.accent.primary },
    GitSignsDeleteNr = { fg = c.states.danger },
    GitSignsAddLn = { bg = c.diff.add },
    GitSignsChangeLn = { bg = c.diff.change },
    GitSignsDeleteLn = { bg = c.diff.delete },
    GitSignsAddInline = { bg = c.diff.add },
    GitSignsChangeInline = { bg = c.diff.change },
    GitSignsDeleteInline = { bg = c.diff.delete },
    GitSignsCurrentLineBlame = { fg = c.fg.fg4, italic = true },

    -- Gitsigns (legacy names)
    SignAdd = { fg = c.states.success },
    SignChange = { fg = c.accent.primary },
    SignDelete = { fg = c.states.danger },

    -- Telescope
    TelescopeNormal = { fg = c.fg.base, bg = c.bg.elevated },
    TelescopeBorder = { fg = c.border.editor, bg = c.bg.elevated },
    TelescopeTitle = { fg = c.fg.base, bold = true },
    TelescopePromptNormal = { fg = c.fg.base, bg = c.bg.inset },
    TelescopePromptBorder = { fg = c.border.inset, bg = c.bg.inset },
    TelescopePromptTitle = { fg = c.fg.base, bg = c.accent.primary },
    TelescopePromptPrefix = { fg = c.accent.primary },
    TelescopePromptCounter = { fg = c.fg.fg3 },
    TelescopeResultsNormal = { fg = c.fg.base, bg = c.bg.elevated },
    TelescopeResultsBorder = { fg = c.border.editor, bg = c.bg.elevated },
    TelescopeResultsTitle = { fg = c.fg.base },
    TelescopePreviewNormal = { fg = c.fg.base, bg = c.bg.editor },
    TelescopePreviewBorder = { fg = c.border.editor, bg = c.bg.editor },
    TelescopePreviewTitle = { fg = c.fg.base },
    TelescopeSelection = { fg = c.fg.base, bg = c.accent.subtle },
    TelescopeSelectionCaret = { fg = c.accent.primary, bg = c.accent.subtle },
    TelescopeMultiSelection = { fg = c.accent.primary, bg = c.accent.subtle },
    TelescopeMultiIcon = { fg = c.accent.primary },
    TelescopeMatching = { fg = c.accent.primary, bold = true },

    -- nvim-cmp
    CmpItemAbbr = { fg = c.fg.base },
    CmpItemAbbrDeprecated = { fg = c.fg.fg3, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.accent.primary, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.accent.primary, bold = true },
    CmpItemKind = { fg = c.fg.fg2 },
    CmpItemMenu = { fg = c.fg.fg3 },
    CmpItemKindText = { fg = c.fg.fg2 },
    CmpItemKindMethod = { fg = c.syntax.func },
    CmpItemKindFunction = { fg = c.syntax.func },
    CmpItemKindConstructor = { fg = c.syntax.type },
    CmpItemKindField = { fg = c.syntax.variable },
    CmpItemKindVariable = { fg = c.syntax.variable },
    CmpItemKindClass = { fg = c.syntax.type },
    CmpItemKindInterface = { fg = c.syntax.type },
    CmpItemKindModule = { fg = c.syntax.namespace },
    CmpItemKindProperty = { fg = c.syntax.variable },
    CmpItemKindUnit = { fg = c.syntax.number },
    CmpItemKindValue = { fg = c.syntax.number },
    CmpItemKindEnum = { fg = c.syntax.type },
    CmpItemKindKeyword = { fg = c.syntax.keyword },
    CmpItemKindSnippet = { fg = c.syntax.escape },
    CmpItemKindColor = { fg = c.syntax.constant },
    CmpItemKindFile = { fg = c.accent.primary },
    CmpItemKindReference = { fg = c.syntax.variable },
    CmpItemKindFolder = { fg = c.accent.primary },
    CmpItemKindEnumMember = { fg = c.syntax.operator },
    CmpItemKindConstant = { fg = c.syntax.constant },
    CmpItemKindStruct = { fg = c.syntax.type },
    CmpItemKindEvent = { fg = c.syntax.func },
    CmpItemKindOperator = { fg = c.syntax.operator },
    CmpItemKindTypeParameter = { fg = c.syntax.type },
    CmpItemKindCopilot = { fg = c.states.success },

    -- nvim-tree
    NvimTreeNormal = { fg = c.fg.fg2, bg = c.bg.window },
    NvimTreeNormalNC = { fg = c.fg.fg2, bg = c.bg.window },
    NvimTreeRootFolder = { fg = c.fg.base, bold = true },
    NvimTreeFolderName = { fg = c.accent.primary },
    NvimTreeFolderIcon = { fg = c.accent.primary },
    NvimTreeOpenedFolderName = { fg = c.accent.primary, bold = true },
    NvimTreeEmptyFolderName = { fg = c.fg.fg3 },
    NvimTreeIndentMarker = { fg = c.border.indent_guide },
    NvimTreeSymlink = { fg = c.syntax.escape },
    NvimTreeSpecialFile = { fg = c.syntax.constant },
    NvimTreeImageFile = { fg = c.syntax.string },
    NvimTreeGitDirty = { fg = c.accent.primary },
    NvimTreeGitNew = { fg = c.states.success },
    NvimTreeGitDeleted = { fg = c.states.danger },
    NvimTreeGitRenamed = { fg = c.accent.primary },
    NvimTreeGitStaged = { fg = c.states.success },
    NvimTreeGitMerge = { fg = c.states.merge },
    NvimTreeGitIgnored = { fg = c.fg.fg3 },
    NvimTreeWindowPicker = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },

    -- neo-tree
    NeoTreeNormal = { fg = c.fg.fg2, bg = c.bg.window },
    NeoTreeNormalNC = { fg = c.fg.fg2, bg = c.bg.window },
    NeoTreeDirectoryName = { fg = c.accent.primary },
    NeoTreeDirectoryIcon = { fg = c.accent.primary },
    NeoTreeRootName = { fg = c.fg.base, bold = true },
    NeoTreeFileName = { fg = c.fg.fg2 },
    NeoTreeFileIcon = { fg = c.fg.fg2 },
    NeoTreeFileNameOpened = { fg = c.accent.primary },
    NeoTreeIndentMarker = { fg = c.border.indent_guide },
    NeoTreeGitAdded = { fg = c.states.success },
    NeoTreeGitConflict = { fg = c.states.warn },
    NeoTreeGitDeleted = { fg = c.states.danger },
    NeoTreeGitIgnored = { fg = c.fg.fg3 },
    NeoTreeGitModified = { fg = c.accent.primary },
    NeoTreeGitUnstaged = { fg = c.accent.primary },
    NeoTreeGitUntracked = { fg = c.states.success },
    NeoTreeGitStaged = { fg = c.states.success },
    NeoTreeFloatBorder = { fg = c.border.editor },
    NeoTreeFloatTitle = { fg = c.fg.base, bold = true },

    -- Lazy.nvim
    LazyNormal = { fg = c.fg.base, bg = c.bg.elevated },
    LazyButton = { fg = c.fg.base, bg = c.bg.inset },
    LazyButtonActive = { fg = c.accent.contrast_on_accent, bg = c.accent.primary },
    LazyH1 = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },
    LazyH2 = { fg = c.syntax.tag, bold = true },
    LazyComment = { fg = c.fg.fg3 },
    LazyCommit = { fg = c.syntax.namespace },
    LazyCommitIssue = { fg = c.syntax.func },
    LazyCommitType = { fg = c.syntax.keyword },
    LazyDimmed = { fg = c.fg.fg4 },
    LazyProp = { fg = c.syntax.variable },
    LazyReasonPlugin = { fg = c.syntax.func },
    LazyReasonEvent = { fg = c.syntax.constant },
    LazyReasonKeys = { fg = c.syntax.keyword },
    LazyReasonStart = { fg = c.states.success },
    LazyReasonRuntime = { fg = c.syntax.namespace },
    LazyReasonFt = { fg = c.syntax.type },
    LazyReasonCmd = { fg = c.syntax.string },
    LazyReasonImport = { fg = c.syntax.operator },
    LazyReasonSource = { fg = c.syntax.escape },
    LazyReasonRequire = { fg = c.syntax.func },
    LazySpecial = { fg = c.accent.primary },
    LazyTaskOutput = { fg = c.fg.base },
    LazyProgressDone = { fg = c.states.success },
    LazyProgressTodo = { fg = c.fg.fg4 },

    -- Mason
    MasonNormal = { fg = c.fg.base, bg = c.bg.elevated },
    MasonHeader = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },
    MasonHeaderSecondary = { fg = c.accent.contrast_on_accent, bg = c.syntax.func, bold = true },
    MasonHighlight = { fg = c.accent.primary },
    MasonHighlightBlock = { fg = c.accent.contrast_on_accent, bg = c.accent.primary },
    MasonHighlightBlockBold = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },
    MasonHighlightSecondary = { fg = c.syntax.func },
    MasonHighlightBlockSecondary = { fg = c.accent.contrast_on_accent, bg = c.syntax.func },
    MasonHighlightBlockBoldSecondary = { fg = c.accent.contrast_on_accent, bg = c.syntax.func, bold = true },
    MasonMuted = { fg = c.fg.fg3 },
    MasonMutedBlock = { fg = c.fg.fg3, bg = c.bg.inset },
    MasonMutedBlockBold = { fg = c.fg.fg3, bg = c.bg.inset, bold = true },

    -- Which-key
    WhichKey = { fg = c.syntax.func },
    WhichKeyGroup = { fg = c.syntax.keyword },
    WhichKeyDesc = { fg = c.fg.base },
    WhichKeySeperator = { fg = c.fg.fg4 },
    WhichKeySeparator = { fg = c.fg.fg4 },
    WhichKeyFloat = { bg = c.bg.elevated },
    WhichKeyBorder = { fg = c.border.editor },
    WhichKeyValue = { fg = c.fg.fg3 },

    -- Indent-blankline
    IndentBlanklineChar = { fg = c.border.indent_guide },
    IndentBlanklineContextChar = { fg = c.border.indent_guide_active },
    IndentBlanklineSpaceChar = { fg = c.border.indent_guide },
    IblIndent = { fg = c.border.indent_guide },
    IblScope = { fg = c.border.indent_guide_active },
    IblWhitespace = { fg = c.border.indent_guide },

    -- Trouble
    TroubleNormal = { fg = c.fg.base, bg = c.bg.elevated },
    TroubleNormalNC = { fg = c.fg.fg2, bg = c.bg.elevated },
    TroubleText = { fg = c.fg.base },
    TroubleCount = { fg = c.accent.contrast_on_accent, bg = c.accent.primary },
    TroubleFile = { fg = c.accent.primary },
    TroubleLocation = { fg = c.fg.fg3 },
    TroublePreview = { fg = c.accent.primary },
    TroubleSource = { fg = c.fg.fg3 },
    TroubleFoldIcon = { fg = c.fg.fg3 },
    TroubleCode = { fg = c.fg.fg3 },
    TroubleError = { fg = c.states.danger },
    TroubleWarning = { fg = c.states.warn },
    TroubleInformation = { fg = c.states.info },
    TroubleHint = { fg = c.fg.fg3 },

    -- Noice
    NoiceCmdline = { fg = c.fg.base },
    NoiceCmdlineIcon = { fg = c.accent.primary },
    NoiceCmdlineIconSearch = { fg = c.syntax.constant },
    NoiceCmdlinePopup = { fg = c.fg.base, bg = c.bg.elevated },
    NoiceCmdlinePopupBorder = { fg = c.border.editor },
    NoiceCmdlinePopupBorderSearch = { fg = c.syntax.constant },
    NoiceConfirm = { fg = c.fg.base, bg = c.bg.elevated },
    NoiceConfirmBorder = { fg = c.border.editor },
    NoiceMini = { fg = c.fg.fg2, bg = c.bg.window },
    NoicePopup = { fg = c.fg.base, bg = c.bg.elevated },
    NoicePopupBorder = { fg = c.border.editor },
    NoicePopupmenu = { fg = c.fg.base, bg = c.bg.elevated },
    NoicePopupmenuBorder = { fg = c.border.editor },
    NoicePopupmenuMatch = { fg = c.accent.primary, bold = true },
    NoicePopupmenuSelected = { bg = c.accent.subtle },
    NoiceScrollbar = { bg = c.bg.inset },
    NoiceScrollbarThumb = { bg = c.fg.fg4 },
    NoiceSplit = { fg = c.fg.base, bg = c.bg.editor },
    NoiceSplitBorder = { fg = c.border.editor },
    NoiceVirtualText = { fg = c.accent.primary },

    -- Notify
    NotifyERRORBorder = { fg = c.states.danger },
    NotifyWARNBorder = { fg = c.states.warn },
    NotifyINFOBorder = { fg = c.states.info },
    NotifyDEBUGBorder = { fg = c.fg.fg3 },
    NotifyTRACEBorder = { fg = c.states.merge },
    NotifyERRORIcon = { fg = c.states.danger },
    NotifyWARNIcon = { fg = c.states.warn },
    NotifyINFOIcon = { fg = c.states.info },
    NotifyDEBUGIcon = { fg = c.fg.fg3 },
    NotifyTRACEIcon = { fg = c.states.merge },
    NotifyERRORTitle = { fg = c.states.danger },
    NotifyWARNTitle = { fg = c.states.warn },
    NotifyINFOTitle = { fg = c.states.info },
    NotifyDEBUGTitle = { fg = c.fg.fg3 },
    NotifyTRACETitle = { fg = c.states.merge },
    NotifyERRORBody = { fg = c.fg.base },
    NotifyWARNBody = { fg = c.fg.base },
    NotifyINFOBody = { fg = c.fg.base },
    NotifyDEBUGBody = { fg = c.fg.base },
    NotifyTRACEBody = { fg = c.fg.base },
    NotifyBackground = { bg = c.bg.elevated },

    -- Dashboard / Alpha
    DashboardHeader = { fg = c.accent.primary },
    DashboardCenter = { fg = c.syntax.func },
    DashboardShortCut = { fg = c.syntax.keyword },
    DashboardFooter = { fg = c.fg.fg3, italic = true },
    AlphaHeader = { fg = c.accent.primary },
    AlphaButtons = { fg = c.syntax.func },
    AlphaShortcut = { fg = c.syntax.keyword },
    AlphaFooter = { fg = c.fg.fg3, italic = true },

    -- Mini plugins
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { bg = c.accent.subtle },
    MiniCursorwordCurrent = { bg = c.accent.subtle },
    MiniIndentscopeSymbol = { fg = c.border.indent_guide_active },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { fg = c.accent.contrast_on_accent, bg = c.accent.primary },
    MiniJump2dSpot = { fg = c.accent.primary, bold = true },
    MiniStarterCurrent = {},
    MiniStarterFooter = { fg = c.fg.fg3, italic = true },
    MiniStarterHeader = { fg = c.accent.primary },
    MiniStarterInactive = { fg = c.fg.fg3 },
    MiniStarterItem = { fg = c.fg.base },
    MiniStarterItemBullet = { fg = c.border.editor },
    MiniStarterItemPrefix = { fg = c.accent.primary },
    MiniStarterSection = { fg = c.syntax.tag, bold = true },
    MiniStarterQuery = { fg = c.accent.primary },
    MiniStatuslineDevinfo = { fg = c.fg.fg2, bg = c.bg.inset },
    MiniStatuslineFileinfo = { fg = c.fg.fg2, bg = c.bg.inset },
    MiniStatuslineFilename = { fg = c.fg.base, bg = c.bg.window },
    MiniStatuslineInactive = { fg = c.fg.fg3, bg = c.bg.window },
    MiniStatuslineModeCommand = { fg = c.accent.contrast_on_accent, bg = c.syntax.constant, bold = true },
    MiniStatuslineModeInsert = { fg = c.accent.contrast_on_accent, bg = c.states.success, bold = true },
    MiniStatuslineModeNormal = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },
    MiniStatuslineModeOther = { fg = c.accent.contrast_on_accent, bg = c.syntax.escape, bold = true },
    MiniStatuslineModeReplace = { fg = c.accent.contrast_on_accent, bg = c.states.danger, bold = true },
    MiniStatuslineModeVisual = { fg = c.accent.contrast_on_accent, bg = c.syntax.keyword, bold = true },
    MiniSurround = { bg = c.syntax.constant, fg = c.bg.editor },
    MiniTablineCurrent = { fg = c.fg.base, bg = c.bg.editor },
    MiniTablineFill = { bg = c.bg.window },
    MiniTablineHidden = { fg = c.fg.fg3, bg = c.bg.window },
    MiniTablineModifiedCurrent = { fg = c.accent.primary, bg = c.bg.editor },
    MiniTablineModifiedHidden = { fg = c.accent.primary, bg = c.bg.window },
    MiniTablineModifiedVisible = { fg = c.accent.primary, bg = c.bg.window },
    MiniTablineTabpagesection = { fg = c.fg.base, bg = c.bg.inset },
    MiniTablineVisible = { fg = c.fg.fg2, bg = c.bg.window },
    MiniTestEmphasis = { bold = true },
    MiniTestFail = { fg = c.states.danger, bold = true },
    MiniTestPass = { fg = c.states.success, bold = true },
    MiniTrailspace = { bg = c.states.danger },

    -- Leap
    LeapMatch = { fg = c.accent.primary, underline = true, nocombine = true },
    LeapLabelPrimary = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },
    LeapLabelSecondary = { fg = c.accent.contrast_on_accent, bg = c.syntax.func, bold = true },
    LeapBackdrop = { fg = c.fg.fg4 },

    -- Flash
    FlashBackdrop = { fg = c.fg.fg4 },
    FlashMatch = { fg = c.accent.primary, underline = true },
    FlashCurrent = { fg = c.accent.primary, bg = c.accent.subtle, bold = true },
    FlashLabel = { fg = c.accent.contrast_on_accent, bg = c.accent.primary, bold = true },
    FlashPrompt = { fg = c.fg.base, bg = c.bg.elevated },
    FlashPromptIcon = { fg = c.accent.primary },

    -- Navic
    NavicIconsFile = { fg = c.accent.primary },
    NavicIconsModule = { fg = c.syntax.namespace },
    NavicIconsNamespace = { fg = c.syntax.namespace },
    NavicIconsPackage = { fg = c.syntax.namespace },
    NavicIconsClass = { fg = c.syntax.type },
    NavicIconsMethod = { fg = c.syntax.func },
    NavicIconsProperty = { fg = c.syntax.variable },
    NavicIconsField = { fg = c.syntax.variable },
    NavicIconsConstructor = { fg = c.syntax.type },
    NavicIconsEnum = { fg = c.syntax.type },
    NavicIconsInterface = { fg = c.syntax.type },
    NavicIconsFunction = { fg = c.syntax.func },
    NavicIconsVariable = { fg = c.syntax.variable },
    NavicIconsConstant = { fg = c.syntax.constant },
    NavicIconsString = { fg = c.syntax.string },
    NavicIconsNumber = { fg = c.syntax.number },
    NavicIconsBoolean = { fg = c.syntax.number },
    NavicIconsArray = { fg = c.syntax.variable },
    NavicIconsObject = { fg = c.syntax.variable },
    NavicIconsKey = { fg = c.syntax.keyword },
    NavicIconsNull = { fg = c.syntax.number },
    NavicIconsEnumMember = { fg = c.syntax.operator },
    NavicIconsStruct = { fg = c.syntax.type },
    NavicIconsEvent = { fg = c.syntax.func },
    NavicIconsOperator = { fg = c.syntax.operator },
    NavicIconsTypeParameter = { fg = c.syntax.type },
    NavicText = { fg = c.fg.fg2 },
    NavicSeparator = { fg = c.fg.fg4 },

    -- Aerial
    AerialLine = { bg = c.accent.subtle },
    AerialGuide = { fg = c.border.indent_guide },
    AerialFileIcon = { fg = c.accent.primary },
    AerialModuleIcon = { fg = c.syntax.namespace },
    AerialNamespaceIcon = { fg = c.syntax.namespace },
    AerialPackageIcon = { fg = c.syntax.namespace },
    AerialClassIcon = { fg = c.syntax.type },
    AerialMethodIcon = { fg = c.syntax.func },
    AerialPropertyIcon = { fg = c.syntax.variable },
    AerialFieldIcon = { fg = c.syntax.variable },
    AerialConstructorIcon = { fg = c.syntax.type },
    AerialEnumIcon = { fg = c.syntax.type },
    AerialInterfaceIcon = { fg = c.syntax.type },
    AerialFunctionIcon = { fg = c.syntax.func },
    AerialVariableIcon = { fg = c.syntax.variable },
    AerialConstantIcon = { fg = c.syntax.constant },
    AerialStringIcon = { fg = c.syntax.string },
    AerialNumberIcon = { fg = c.syntax.number },
    AerialBooleanIcon = { fg = c.syntax.number },
    AerialArrayIcon = { fg = c.syntax.variable },
    AerialObjectIcon = { fg = c.syntax.variable },
    AerialKeyIcon = { fg = c.syntax.keyword },
    AerialNullIcon = { fg = c.syntax.number },
    AerialEnumMemberIcon = { fg = c.syntax.operator },
    AerialStructIcon = { fg = c.syntax.type },
    AerialEventIcon = { fg = c.syntax.func },
    AerialOperatorIcon = { fg = c.syntax.operator },
    AerialTypeParameterIcon = { fg = c.syntax.type },

    -- Bufferline
    BufferLineIndicatorSelected = { fg = c.accent.primary },
    BufferLineFill = { bg = c.bg.window },

    -- Barbar
    BufferCurrent = { fg = c.fg.base, bg = c.bg.editor },
    BufferCurrentIndex = { fg = c.accent.primary, bg = c.bg.editor },
    BufferCurrentMod = { fg = c.accent.primary, bg = c.bg.editor },
    BufferCurrentSign = { fg = c.accent.primary, bg = c.bg.editor },
    BufferCurrentTarget = { fg = c.states.danger, bg = c.bg.editor, bold = true },
    BufferVisible = { fg = c.fg.fg2, bg = c.bg.window },
    BufferVisibleIndex = { fg = c.fg.fg2, bg = c.bg.window },
    BufferVisibleMod = { fg = c.accent.primary, bg = c.bg.window },
    BufferVisibleSign = { fg = c.fg.fg3, bg = c.bg.window },
    BufferVisibleTarget = { fg = c.states.danger, bg = c.bg.window, bold = true },
    BufferInactive = { fg = c.fg.fg3, bg = c.bg.window },
    BufferInactiveIndex = { fg = c.fg.fg3, bg = c.bg.window },
    BufferInactiveMod = { fg = c.accent.primary, bg = c.bg.window },
    BufferInactiveSign = { fg = c.fg.fg4, bg = c.bg.window },
    BufferInactiveTarget = { fg = c.states.danger, bg = c.bg.window, bold = true },
    BufferTabpages = { fg = c.fg.base, bg = c.bg.inset },
    BufferTabpageFill = { bg = c.bg.window },

    -- Snacks
    SnacksNormal = { fg = c.fg.base, bg = c.bg.elevated },
    SnacksDashboardHeader = { fg = c.accent.primary },
    SnacksDashboardFooter = { fg = c.fg.fg3, italic = true },
    SnacksDashboardIcon = { fg = c.accent.primary },
    SnacksDashboardKey = { fg = c.syntax.keyword },
    SnacksDashboardDesc = { fg = c.fg.base },
    SnacksDashboardFile = { fg = c.syntax.func },
    SnacksDashboardDir = { fg = c.fg.fg3 },
    SnacksDashboardSpecial = { fg = c.syntax.constant },

    -- Render Markdown
    RenderMarkdownH1Bg = { bg = c.diff.add },
    RenderMarkdownH2Bg = { bg = c.diff.change },
    RenderMarkdownH3Bg = { bg = c.diff.text },
    RenderMarkdownH4Bg = { bg = c.accent.subtle },
    RenderMarkdownH5Bg = { bg = c.bg.inset },
    RenderMarkdownH6Bg = { bg = c.bg.inset },
    RenderMarkdownCode = { bg = c.bg.inset },
    RenderMarkdownCodeInline = { bg = c.bg.inset },
    RenderMarkdownBullet = { fg = c.syntax.tag },
    RenderMarkdownQuote = { fg = c.syntax.comment },
    RenderMarkdownTableHead = { fg = c.syntax.tag, bold = true },
    RenderMarkdownTableRow = { fg = c.fg.base },
    RenderMarkdownTableFill = { fg = c.fg.fg4 },
    RenderMarkdownLink = { fg = c.accent.link, underline = true },
    RenderMarkdownMath = { fg = c.syntax.number },
    RenderMarkdownChecked = { fg = c.states.success },
    RenderMarkdownUnchecked = { fg = c.fg.fg3 },

    -- Blink.cmp
    BlinkCmpMenu = { fg = c.fg.base, bg = c.bg.elevated },
    BlinkCmpMenuBorder = { fg = c.border.editor, bg = c.bg.elevated },
    BlinkCmpMenuSelection = { bg = c.accent.subtle },
    BlinkCmpLabel = { fg = c.fg.base },
    BlinkCmpLabelDeprecated = { fg = c.fg.fg3, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.accent.primary, bold = true },
    BlinkCmpKind = { fg = c.fg.fg2 },
    BlinkCmpKindText = { fg = c.fg.fg2 },
    BlinkCmpKindMethod = { fg = c.syntax.func },
    BlinkCmpKindFunction = { fg = c.syntax.func },
    BlinkCmpKindConstructor = { fg = c.syntax.type },
    BlinkCmpKindField = { fg = c.syntax.variable },
    BlinkCmpKindVariable = { fg = c.syntax.variable },
    BlinkCmpKindClass = { fg = c.syntax.type },
    BlinkCmpKindInterface = { fg = c.syntax.type },
    BlinkCmpKindModule = { fg = c.syntax.namespace },
    BlinkCmpKindProperty = { fg = c.syntax.variable },
    BlinkCmpKindUnit = { fg = c.syntax.number },
    BlinkCmpKindValue = { fg = c.syntax.number },
    BlinkCmpKindEnum = { fg = c.syntax.type },
    BlinkCmpKindKeyword = { fg = c.syntax.keyword },
    BlinkCmpKindSnippet = { fg = c.syntax.escape },
    BlinkCmpKindColor = { fg = c.syntax.constant },
    BlinkCmpKindFile = { fg = c.accent.primary },
    BlinkCmpKindReference = { fg = c.syntax.variable },
    BlinkCmpKindFolder = { fg = c.accent.primary },
    BlinkCmpKindEnumMember = { fg = c.syntax.operator },
    BlinkCmpKindConstant = { fg = c.syntax.constant },
    BlinkCmpKindStruct = { fg = c.syntax.type },
    BlinkCmpKindEvent = { fg = c.syntax.func },
    BlinkCmpKindOperator = { fg = c.syntax.operator },
    BlinkCmpKindTypeParameter = { fg = c.syntax.type },
    BlinkCmpDoc = { fg = c.fg.base, bg = c.bg.elevated },
    BlinkCmpDocBorder = { fg = c.border.editor, bg = c.bg.elevated },
    BlinkCmpDocSeparator = { fg = c.border.editor },
    BlinkCmpSignatureHelp = { fg = c.fg.base, bg = c.bg.elevated },
    BlinkCmpSignatureHelpBorder = { fg = c.border.editor, bg = c.bg.elevated },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.accent.primary, bold = true },
    BlinkCmpScrollBarThumb = { bg = c.fg.fg4 },
    BlinkCmpScrollBarGutter = { bg = c.bg.inset },
    BlinkCmpGhostText = { fg = c.fg.fg4 },
    BlinkCmpSource = { fg = c.fg.fg3 },
  }
end

return M
